### PR TITLE
fix two error

### PR DESCRIPTION
**Pull request by ChIaSg**
1.flaskapp/forms.py
ImportError: No module named 'urlparse'

2.flaskapp/__init__.py
TypeError: the JSON object must be str, not 'bytes'

### CODE REVIEW

**Comment by amorey** [comment]
Thanks for submitting this pull request. Which problems does this address?

**Comment by ChIaSg** [comment]
It will throws an error when execute the command：python scripts/create_db.py

That will fix it.

**Comment by amorey** [comment]
I see. It looks like you're trying to modify the project so it runs on Python3. After I applied the changes I tried running the development server and I got this error (partial traceback):
```
  File "/home/vagrant/envs/flaskapp3-env/lib/python3.4/site-packages/itsdangerous.py", line 550, in dump_payload
    return want_bytes(self.serializer.dumps(obj))
  File "/home/vagrant/envs/flaskapp3-env/lib/python3.4/site-packages/itsdangerous.py", line 51, in dumps
    return json.dumps(obj, separators=(',', ':'))
  File "/usr/lib/python3.4/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.4/json/encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.4/json/encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
```

Do you have the app working with Python3? 

Also:
 - I think you can remove the line `import urlparse` altogether.
 - Is the file `.idea/vcs.xml` in the pull request necessary?

**Comment by amorey** [comment]
I incorporated some of your changes into the master. Can you check out the master and try running it again?

**Comment by ChIaSg** [comment]
Yes, I use Python3, and `import urlparse` is not necessary.
`.idea/vcs.xml` is not necessary too.

**Comment by amorey** [comment]
Ok, thanks for the update. I made these changes in the master so `flaskapp` should work with Python3 now.

**Pull request closed without merging**
